---
    name: 1. Image build and push to ecr
    on: 
      push:
        branches: [master]
      pull_request:
        branches:
          - main
        paths-ignore: 
          - '.github/**'
        types:
          - opened
          - synchronize
    jobs:
      Build_and_push_image_to_ecr:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
    
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-south-1
    
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1
    
          - name: Build, tag, and push image to amazon ECR
            env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              ECR_REPOSITORY: ${{ github.event.repository.name }}
            run: |
              IMAGE_TAG_prefix=$(echo "${{ github.event.pull_request.number || github.event.push.ref }}" | sed -e 's!^refs/heads/!!')
              IMAGE_TAG_suffix=$(echo "${{ github.sha }}" | cut -c1-8)
              IMAGE_TAG=$IMAGE_TAG_prefix-$IMAGE_TAG_suffix
              docker build -t $ECR_REGISTRY/$ECR_REPOSITORY .
              docker push $ECR_REGISTRY/$ECR_REPOSITORY
              docker tag $ECR_REGISTRY/$ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
              
          - name: Logout of amazon ECR
            if: always()
            run: docker logout ${{ steps.login-ecr.outputs.registry }}
        
